package pkgfinal;

/**
 *
 * @author Mihai
 */
public class Meniu extends javax.swing.JFrame {
    public Meniu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_mesaj = new javax.swing.JLabel();
        jButton_plata_cu_ora = new javax.swing.JButton();
        jButton_state_de_functii = new javax.swing.JButton();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel_mesaj.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_mesaj.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel_mesaj.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mesaj.setText("Bine ati venit!");
        jPanel1.add(jLabel_mesaj);
        jLabel_mesaj.setBounds(175, 100, 150, 32);

        jButton_plata_cu_ora.setBackground(new java.awt.Color(255, 255, 255));
        jButton_plata_cu_ora.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_plata_cu_ora.setText("Plata cu ora");
        jButton_plata_cu_ora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_plata_cu_oraMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_plata_cu_ora);
        jButton_plata_cu_ora.setBounds(175, 200, 190, 30);

        jButton_state_de_functii.setBackground(new java.awt.Color(255, 255, 255));
        jButton_state_de_functii.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_state_de_functii.setText("State de functii");
        jButton_state_de_functii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_state_de_functiiMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_state_de_functii);
        jButton_state_de_functii.setBounds(175, 300, 220, 30);

        jLabel_background.setIcon(new javax.swing.ImageIcon("D:\\Documents\\FMI\\Anul 3\\Licenta\\Final\\500.jpg")); // NOI18N
        jLabel_background.setText("jLabel3");
        jPanel1.add(jLabel_background);
        jLabel_background.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_plata_cu_oraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_plata_cu_oraMouseClicked
        PlataCuOraV1 plata = new PlataCuOraV1();
        plata.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_plata_cu_oraMouseClicked

    private void jButton_state_de_functiiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_state_de_functiiMouseClicked
        StateDeFunctiiV1 state = new StateDeFunctiiV1();
        state.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_state_de_functiiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meniu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_plata_cu_ora;
    private javax.swing.JButton jButton_state_de_functii;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_mesaj;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
